### ISSUE TITLE
"PreauthAmount" is unrecognised by "Altapay\Response\ReserveSubscriptionResponse"

### ISSUE THREAD

**Issue by AJenbo** [AltaPay/api-php#18]
When creating a subscription we get the following error:
`The parameter "PreauthAmount" does not have a setter or a property in class "Altapay\Response\ReserveSubscriptionResponse"`

**Comment by BushraAsif** [comment]
Hi @AJenbo , thanks for the heads up and providing a fixes. The change will be review and merged soon.

**Comment by AJenbo** [comment]
Thanks :smiley:
