### ISSUE TITLE
Redundant assigning of shopOrderId in Callback

### ISSUE THREAD

**Issue by robjarWA** [AltaPay/api-php#48]
The following lines https://github.com/AltaPay/api-php/blob/main/src/Api/Ecommerce/Callback.php#L58-L60:
```
if (isset($this->postedData['shop_orderid'])) {
  $response->shopOrderId = $this->postedData['shop_orderid'];
}
```

are repeated here: https://github.com/AltaPay/api-php/blob/main/src/Api/Ecommerce/Callback.php#L86-L88

**Comment by shahbaz-mehar** [comment]
@robjarWA This is fixed now; the redundant code has been removed.
https://github.com/AltaPay/api-php/releases/tag/3.4.3

**Comment by shahbaz-mehar** [comment]
@robjarWA This is fixed now; the redundant code has been removed.
https://github.com/AltaPay/api-php/releases/tag/3.4.3
